# Generated by Django 4.1.2 on 2022-10-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.DateTimeField(auto_now=True)),
                ('data_atualizacao', models.DateTimeField()),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('partida_previsao', models.DateTimeField(auto_now=True)),
                ('chegada_previsao', models.DateTimeField()),
                ('partida_real', models.DateTimeField(auto_now=True)),
                ('chegada_real', models.DateTimeField()),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aeroporto_origem', models.CharField(max_length=5)),
                ('aeroporto_destino', models.CharField(max_length=5)),
                ('conexoes', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'rota',
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_de_voo', models.CharField(max_length=10)),
                ('estado_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.estado')),
                ('horarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.horarios')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.rota')),
            ],
            options={
                'db_table': 'voo',
            },
        ),
        migrations.CreateModel(
            name='Voo_Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.estado')),
                ('id_voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.voo')),
            ],
            options={
                'db_table': 'voo_estado',
            },
        ),
    ]
