# Generated by Django 4.1.2 on 2022-10-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_estado_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='partida_previsao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='partida_real',
            field=models.DateTimeField(),
        ),
    ]
