# Generated by Django 4.1.2 on 2022-10-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_horarios_partida_previsao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voo_estado',
            old_name='id_estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='voo_estado',
            old_name='id_voo',
            new_name='voo',
        ),
    ]
