# Generated by Django 4.1.1 on 2022-11-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_id_estado_voo_estado_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='chegada_real',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='partida_real',
            field=models.DateTimeField(null=True),
        ),
    ]
