# Generated by Django 4.1.1 on 2022-11-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_estado_id_alter_horarios_id_alter_rota_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='companhia_aerea',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
